#!/usr/bin/env python3
"""
deploy_rules.py — copy custom rules into the Wazuh manager container and reload.

Run this after adding or modifying any rule file in rules/.

Usage:
    python scripts/deploy_rules.py
    python scripts/deploy_rules.py --container wazuh-manager --dry-run
"""

import argparse
import subprocess
import sys
from pathlib import Path

RULES_DIR = Path(__file__).parent.parent / "rules"
WAZUH_RULES_PATH = "/var/ossec/etc/rules/local_rules.xml"


def collect_rules(rules_dir: Path) -> str:
    """
    Walk the rules directory, read all .xml files, and merge them
    into a single XML document for Wazuh.
    """
    parts = []
    for xml_file in sorted(rules_dir.rglob("*.xml")):
        content = xml_file.read_text().strip()
        # Strip outer <group> tags if present — we'll wrap everything together
        parts.append(f"\n  <!-- Source: {xml_file.relative_to(rules_dir)} -->")
        parts.append(content)

    merged = "<!-- Auto-generated by deploy_rules.py — do not edit directly -->\n"
    merged += "\n".join(parts)
    return merged


def run(cmd: list, dry_run: bool = False) -> int:
    print(f"  $ {' '.join(cmd)}")
    if dry_run:
        return 0
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr.strip()}", file=sys.stderr)
    elif result.stdout.strip():
        print(f"  {result.stdout.strip()}")
    return result.returncode


def main():
    parser = argparse.ArgumentParser(description="Deploy Wazuh rules to manager container")
    parser.add_argument("--container", default="siem-detection-lab-wazuh-manager-1",
                        help="Docker container name")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--validate-only", action="store_true",
                        help="Check XML syntax without deploying")
    args = parser.parse_args()

    print(f"Collecting rules from {RULES_DIR}...")
    rule_files = list(RULES_DIR.rglob("*.xml"))
    if not rule_files:
        print("No rule files found.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(rule_files)} rule file(s):")
    for f in sorted(rule_files):
        print(f"  {f.relative_to(RULES_DIR)}")

    merged = collect_rules(RULES_DIR)

    if args.validate_only:
        print("\nXML syntax check:")
        try:
            import xml.etree.ElementTree as ET
            ET.fromstring(f"<rules>{merged}</rules>")
            print("  OK — no syntax errors found")
        except ET.ParseError as e:
            print(f"  FAIL — {e}", file=sys.stderr)
            sys.exit(1)
        return

    # Write merged rules to a temp file then copy into container
    tmp_path = Path("/tmp/cloudsoc_local_rules.xml")
    if not args.dry_run:
        tmp_path.write_text(merged)
        print(f"\nWrote merged rules to {tmp_path}")

    print(f"\nDeploying to container: {args.container}")

    rc = run(["docker", "cp", str(tmp_path), f"{args.container}:{WAZUH_RULES_PATH}"], args.dry_run)
    if rc != 0:
        print("Failed to copy rules. Is the container running?", file=sys.stderr)
        sys.exit(1)

    print("Reloading Wazuh manager...")
    rc = run(["docker", "exec", args.container, "/var/ossec/bin/ossec-control", "reload"], args.dry_run)
    if rc != 0:
        # Newer Wazuh versions use wazuh-control
        rc = run(["docker", "exec", args.container, "/var/ossec/bin/wazuh-control", "reload"], args.dry_run)

    if rc == 0:
        print("\nDone. Rules deployed and manager reloaded.")
        print("Check Kibana → Security Events to see new detections.")
    else:
        print("\nDeploy failed. Check docker logs for details.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
